version: "3.1"
services:
  cockroachdb:
    image: cockroachdb/cockroach:latest-v22.1
    command: start-single-node --cluster-name=example-single-node --insecure
    ports:
      - 26257:26257
    environment:
      COCKROACH_DATABASE: "knex_example"
